### ISSUE TITLE
Lackluster Wiki

### ISSUE THREAD

**Issue by Drakoflame** [EwyBoy/Cultivated-Tech#10]
Now... this isn't an issue with the mod per se... rather the documentation of the mod, that doesn't require the mod be installed... While I trust that the mod add some wonderful stuff, but the fact that there are only... 2 things in the wiki tab (on curseforge), being the Ecoflamer and the Magma lily, while clearly on the curseforge page itself there are 3 items and features no-where mentioned in the barren wiki...

I understand that your probably very busy with things in real life and other mods, but would it be possible to please update the wiki, or put the information somewhere it can be accessed, or put some links to proper mod reviews, or user-made wikis on the page. I've been looking at this mod ever since it came out, wondering what the heck it does, and I really don't like downloading mods without knowing that they are, what I can expect, or have somewhere to fall back on to look up why the thing blew up after I added the stuff...

**Comment by EwyBoy** [comment]
hey @Drakoflame! Thanks for your feedback, yes I know the documentation is bad. The mod is in a development phase and things change so rapidly that I struggle to document it all. I been thinking about adding some documentation on the FTB Wiki and get some of my friends to help me document it with me. I will also rework the CurseForge page once I get the time. I will keep this issue open to constantly remind me to improve the documentation.

-Ewy

**Comment by Drakoflame** [comment]
Awesome! I can't wait to see what does get added to the wiki, whether it be a bunch of redundant things I have from other mods, and subsequently replace them, or if its unique in its own right and becomes required for enjoyment!

**Comment by EwyBoy** [comment]
https://cultivated-tech.wikia.com/wiki/Cultivated_Tech_Wiki
