### ISSUE TITLE
Stuck on world load

### ISSUE THREAD

**Issue by MasterEnderman** [EwyBoy/Cultivated-Tech#4]
Added Cultivated Tech loaded my test world and the game freezes. After shuting it down thats what I found in the console: https://pastebin.com/2MhpBhdW

Cultivated Tech: 17w50-A
Forge: 14.23.1.2562

**Comment by EwyBoy** [comment]
The issue comes from Hunger Overhaul doing some shady core modding / ASM and not bulletproofing its code. I can try to fix it on my end. But you should really talk to the devs for  Hunger Overhaul / Apple Core and tell em to add some try / catch and null checks so stuff like this does not happen.

**Comment by EwyBoy** [comment]
https://minecraft.curseforge.com/projects/cultivated-tech/files/2509945

**Comment by squeek502** [comment]
Unless I'm missing something, this doesn't appear to be related to AppleCore or Hunger Overhaul. The only ASM involved is Forge's, which is being used to call its tooltip events.

Your [ItemVape.getItemUseAction](https://github.com/EwyBoy/Cultivated-Tech/blob/master/src/main/java/com/ewyboy/cultivatedtech/common/items/ItemVape.java#L68-L86) method has two problems that I can see:
- It seems to be assuming that it's only called at specific times, but that isn't safe to assume. It should be treated as a getter that can be called at any time for any reason, so spawning particles within it is *not* a good idea.
- The method will crash if it's ever called on a dedicated server, as it references the client-only `Minecraft` and `EntityPlayerSP` classes.

**Comment by EwyBoy** [comment]
Okey, I will get this sorted out.
