### ISSUE TITLE
Putting rftools powercell above Withered Ecoflamer causes crash

### ISSUE THREAD

**Issue by choekstr** [EwyBoy/Cultivated-Tech#5]
I created a withered Ecoflamer, placed it on grass and put a rftools powercell above it, touching, without any wires/conduits/ducts.  It crashed immediately upon touching the two and I can't seem to load the world anymore otherwise I would post screenshot of the setup (but it should be straightforward).

Here is the crashlog output.  I can't tell if this is an rftools issues or a cultivated-tech issue so I figured I would start here first.
[https://pastebin.com/yqWf2nw2](https://pastebin.com/yqWf2nw2)

**Comment by EwyBoy** [comment]
Looking into it now, give me a few minutes.

**Comment by choekstr** [comment]
Seems that if I use a CoFH/TE leadstone fluxduct in-between the two it works fine.
I am using the latest versions of both mods in the EOD:Synthesis modpack.  

Cultivated Tech-17w50-B-1.12.2.jar
rftools-1.12-7.15.jar

Here is what I did to get it to stop crashing: [Working Setup](http://i219.photobucket.com/albums/cc191/choekstr/Cultivated-Tech_1.jpg)

**Comment by EwyBoy** [comment]
Been testing this for a while now and still not been able to reproduce the bug.
Been running in single player:
`
Cultivated Tech-17w50-B-1.12.2.jar
rftools-1.12-7.15
mcjtylib-1.12-2.5.0
`
I added in some extra code to the Ecoflamer now, so it should catch the null pointer exception (the crash, before it manages to do any harm). If it still crashes after my new build is up, it is probably on RF-Tools end in this part of the code:
`  
    at mcjty.rftools.blocks.powercell.PowerCellTileEntity.getNetwork(PowerCellTileEntity.java:156)
    at mcjty.rftools.blocks.powercell.PowerCellTileEntity.receiveEnergyMulti(PowerCellTileEntity.java:482)
    at mcjty.rftools.blocks.powercell.PowerCellTileEntity.receiveEnergyFacing(PowerCellTileEntity.java:471)
    at mcjty.rftools.blocks.powercell.PowerCellTileEntity.receiveEnergy(PowerCellTileEntity.java:458)
`

**Comment by choekstr** [comment]
Ok, brilliant.  I will update on my end and let you know if I encounter it again.  Thanks for jumping on this and testing and I figured it would be tough to replicate.

**Comment by EwyBoy** [comment]
Here is the new build https://minecraft.curseforge.com/projects/cultivated-tech/files/2511677
