### ISSUE TITLE
Crash: BlockSwapper - Tesselating Block Model

### ISSUE THREAD

**Issue by sdaddy** [EwyBoy/Cultivated-Tech#6]
Mod Version: 17w51-A-1.12.2
Forge Version: 14.23.1.2577
Crash Report: https://gist.github.com/sdaddy/b357fad81f944738b11ac12a667a4e72

I was playing around with the mod; trying to figure out what the blockswapper did. I placed two different blocks (the two types of bricks from the mod) on the sides of the blockswapper and right-clicked it to see if they would swap sides. It made the noise, but nothing happened so I used a pickaxe to break one of the blocks and crashed.

**Comment by EwyBoy** [comment]
This is fixed now as the block has been removed.
